name: 'OpenFGA Model Deploy Action'
description: 'Github Action for deploying your Authorization Model to an OpenFGA Store'
branding:
  icon: align-center
  color: green

inputs:
  api-url:
    description: The OpenFGA server to import the Authorization Model into
    required: true
  api-token:
    description: The shared secret for the server
  store-id:
    description: The store to import the Authorization Model into
    required: true
  model-file-path:
    description: The file path of the model to be imported
    required: false
  model:
    description: The model to be imported into. The characters should be escaped. The value from here will be used if model-file-path is empty
    required: false
  format:
    description: Authorization model input format. Can be "fga" or "json", defaults to auto-detecting from the file extension
    required: false

outputs:
  authorization_model_id:
    description: The ID of the deployed Authorization Model
    value: ${{ steps.deploy.outputs.authorization_model_id }}


runs:
  using: composite
  steps:
    - name: Install OpenFGA CLI
      uses: jaxxstorm/action-install-gh-release@v1.10.0
      with:
        repo: openfga/cli
        cache: enable
    - name: Install JQ
      uses: dcarbone/install-jq-action@v2
    - name: Deploy
      id: 'deploy'
      shell: bash
      run: |
        if [ "${{ inputs.model-file-path }}" ]
        then
          fga_output=$(fga model write --api-url=${{ inputs.api-url }} --api-token=${{ inputs.api-token }} --store-id=${{ inputs.store-id }} --file=${{ inputs.model-file-path }})
        else
          fga_output=$(fga model write --api-url=${{ inputs.api-url }} --api-token=${{ inputs.api-token }} --store-id=${{ inputs.store-id }} --format=${{ inputs.format }} ${{ inputs.model }})
        fi
        echo "$fga_output"
        
        authorization_model_id=$(echo "$fga_output" | jq -r '.authorization_model_id')
        echo "authorization_model_id=${authorization_model_id}"
        echo "authorization_model_id=${authorization_model_id}" >> "$GITHUB_OUTPUT"
        echo "fga_deploy_output=$fga_output" >> "$GITHUB_OUTPUT"
